name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: cache-node-modules-${{ hashFiles('package-lock.json') }}
    - uses: actions/setup-node@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        node-version: 14.x
    - name: Install Packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - name: Run tests
      run: npm test
