name: Functional tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  electron@latest:
    name: Functional tests with electron@latest
    uses: ./.github/workflows/functional-tests-install.yml      
    steps:
    - name: Run tests
      run: npm test:functional
