name: Functional tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  electron-latest:
    name: electron@latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/functional-tests-install 
      name: Install dependencies
    - name: Run tests
      run: npm test:functional
