name: Functional tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  install:
    name: Install dependencies
    uses: ./.github/workflows/functional-tests-install.yml
    
  electron-latest:
    name: electron@latest
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Run tests
      run: npm test:functional
